"""empty message

Revision ID: 493e9552b893
Revises: 983726ce1250
Create Date: 2025-03-30 01:40:30.185645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493e9552b893'
down_revision = '983726ce1250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False, server_default=sa.text("''")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
