"""empty message

Revision ID: 5c4a05fee534
Revises: 493e9552b893
Create Date: 2025-03-30 16:53:10.925146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4a05fee534'
down_revision = '493e9552b893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_setter_player_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bot', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_bot')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('title_setter_player_id')

    # ### end Alembic commands ###
