"""Add created_at to Room model

Revision ID: 785f75303997
Revises: 99a7c1f3ba08
Create Date: 2025-04-01 16:48:05.755305

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '785f75303997'
down_revision = '99a7c1f3ba08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, default=sa.func.now(), server_default=sa.func.now()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.create_table('_alembic_tmp_vote',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('voter_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('votes', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='fk_vote_room_id_room'),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], name='fk_vote_voter_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_vote')
    )
    # ### end Alembic commands ###
