"""empty message

Revision ID: 983726ce1250
Revises: 0b1669b09d0c
Create Date: 2025-03-29 22:50:35.110099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983726ce1250'
down_revision = '0b1669b09d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
