"""empty message

Revision ID: 9adf18c580dd
Revises: 5c4a05fee534
Create Date: 2025-03-30 19:59:41.416817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adf18c580dd'
down_revision = '5c4a05fee534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('voter_id', sa.INTEGER(), nullable=False),
    sa.Column('vote1', sa.INTEGER(), nullable=False),
    sa.Column('vote2', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='fk_votes_room_id_room'),
    sa.ForeignKeyConstraint(['vote1'], ['user.id'], name='fk_votes_vote1_user'),
    sa.ForeignKeyConstraint(['vote2'], ['user.id'], name='fk_votes_vote2_user'),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], name='fk_votes_voter_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_votes')
    )
    # ### end Alembic commands ###
