"""empty message

Revision ID: d9178af2341e
Revises: 
Create Date: 2025-03-29 22:27:11.827448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9178af2341e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_player_notes_note'), 'note', ['notes'], ['id'])

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_player_notes_note'), type_='foreignkey')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
